PWAHStackTC: PWAHStackTC< B > Class Template Reference
PWAHStackTC< B > Class Template Reference
#include <PWAHStackTC.h>
Public Member Functions
PWAHStackTC (Graph &graph)
virtual ~PWAHStackTC ()
void computeTransitiveClosure (bool reflexive, bool storeComponentMembers, int minOutDegreeForMultiOR)
string tcToString ()
long countNumberOfEdgesInTC ()
long countNumberOfEdgesInCondensedTC ()
Counts the number of edges in the condensed transitive closure. This includes all kinds of self-loops.
long countNumberOfEdgesInCondensedTC (bool ignoreSelfLoops, bool ignoreSingletonSelfLoops)
Counts the number of edges in the condensed transitive closure. Optionally, some kinds of self-loops are not counted.
float countAverageNumberOfIntervals (bool countNulls=true)
int countMaxNumberOfIntervals ()
long countTotalNumberOfIntervals ()
double computeLocalClusteringCoefficient (int componentIndex)
double computeAverageLocalClusteringCoefficient ()
int getNumberOfComponents ()
void writeToChacoFile (string filename)
bool reachable (unsigned int src, unsigned int dst)
Answers a reachability query for two vertices 'src' and 'dst'.
void reachablepairs (vector< unsigned int > &sources, vector< unsigned int > &targets, vector< vector< unsigned int > > &reachable_pairs)
long memoryUsedByBitSets ()
long totalMemoryUsage ()
string getStatistics ()
string algorithmName ()
long memoryUsedByIntervalLists ()
template<>
void reachablepairs (vector< unsigned int > &sources, vector< unsigned int > &targets, vector< vector< unsigned int > > &reachable)
template<>
long countTotalNumberOfIntervals ()
template<>
int countMaxNumberOfIntervals ()
template<>
float countAverageNumberOfIntervals (bool countNulls)
template<>
string getStatistics ()
Public Member Functions inherited from TransitiveClosureAlgorithm
TransitiveClosureAlgorithm ()
virtual ~TransitiveClosureAlgorithm ()
Private Member Functions
bool componentHasSelfLoop (int componentIndex)
void dfsVisit (unsigned int vertexIndex)
Private Attributes
Graph * _graph
vector< B * > _componentSuccessors
int * _vertexComponents
bool _storeComponentVertices
vector< int * > _componentVertices
vector< unsigned int > _componentSizes
DynamicBitSet _visited
DynamicStack * _vStack
DynamicStack * _cStack
unsigned int * _savedVStackSize
unsigned int * _savedCStackSize
unsigned int * _vertexCandidateComponentRoot
StaticBitSet * _vertexSelfLoop
int * _vertexDFSSeqNo
int _lastDFSSeqNo
int _lastComponentIndex
bool _reflexitive
int _minOutDegreeForMultiOR
PerformanceTimer _mergeTimer
Friends
class BitSetTester< IntervalBitSet >
class BitSetTester< WAHBitSet >
class BitSetTester< PWAHBitSet< 2 > >
class BitSetTester< PWAHBitSet< 4 > >
class BitSetTester< PWAHBitSet< 8 > >
Detailed Description
template<class B>
class PWAHStackTC< B >
Definition at line 37 of file PWAHStackTC.h.
Constructor & Destructor Documentation
template<class B > PWAHStackTC< B >::PWAHStackTC (Graph & graph)
Definition at line 36 of file PWAHStackTC.cpp.
template<class B > PWAHStackTC< B >::~PWAHStackTC () virtual
Definition at line 40 of file PWAHStackTC.cpp.
Member Function Documentation
template<class B > string PWAHStackTC< B >::algorithmName () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 756 of file PWAHStackTC.cpp.
template<class B > bool PWAHStackTC< B >::componentHasSelfLoop (int componentIndex) private
Definition at line 436 of file PWAHStackTC.cpp.
template<class B > double PWAHStackTC< B >::computeAverageLocalClusteringCoefficient () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 787 of file PWAHStackTC.cpp.
template<class B > double PWAHStackTC< B >::computeLocalClusteringCoefficient (int componentIndex)
Definition at line 797 of file PWAHStackTC.cpp.
References StaticBitSet::get(), BitSetIterator::next(), and StaticBitSet::set().
template<class B > void PWAHStackTC< B >::computeTransitiveClosure (bool reflexive, bool storeComponentMembers, int minOutDegreeForMultiOR) virtual
Implements TransitiveClosureAlgorithm.
Definition at line 48 of file PWAHStackTC.cpp.
Referenced by doSourcesTargetsReachability().
template<class B> float PWAHStackTC< B >::countAverageNumberOfIntervals (bool countNulls = true)
template<> float PWAHStackTC< IntervalBitSet >::countAverageNumberOfIntervals (bool countNulls)
Definition at line 723 of file PWAHStackTC.cpp.
template<class B> int PWAHStackTC< B >::countMaxNumberOfIntervals ()
template<> int PWAHStackTC< IntervalBitSet >::countMaxNumberOfIntervals ()
Definition at line 712 of file PWAHStackTC.cpp.
template<class B > long PWAHStackTC< B >::countNumberOfEdgesInCondensedTC () virtual
Counts the number of edges in the condensed transitive closure. This includes all kinds of self-loops.
Edges in the condensed transitive closure are basically all edges between components. Duplicate edges between components (i.e. when multiple vertices from component A are connected to one or more vertices in component B) are ignored.
Implements TransitiveClosureAlgorithm.
Definition at line 372 of file PWAHStackTC.cpp.
template<class B > long PWAHStackTC< B >::countNumberOfEdgesInCondensedTC (bool ignoreSelfLoops, bool ignoreSingletonSelfLoops) virtual
Counts the number of edges in the condensed transitive closure. Optionally, some kinds of self-loops are not counted.
Edges in the condensed transitive closure are basically all edges between components. Duplicate edges between components (i.e. when multiple vertices from component A are connected to one or more vertices in component B) are ignored.
Parameters
ignoreSelfLoops Ignore all self-loops in the condensed transitive closure (note that a component has a self loop when the number of vertices in the component > 1!)
ignoreSingletonSelfLoops Ignore all self-loops of singleton components (components consisting of only one vertex)
Implements TransitiveClosureAlgorithm.
Definition at line 389 of file PWAHStackTC.cpp.
References BitSetIterator::next().
template<class B > long PWAHStackTC< B >::countNumberOfEdgesInTC () virtual
Brute force without using iterators: int compA, compB; long counter = 0; for (int i = 0; i < _graph->getNumberOfVertices(); i++){ compA = _vertexComponents[i]; for (int j = 0; j < _graph->getNumberOfVertices(); j++){ compB = _vertexComponents[j];
if (_componentSuccessors[compA] != NULL && _componentSuccessors[compA]->get(compB)) counter++; } }
return counter;
for (int i = 0; i < _componentSizes.size(); i++){ if (_componentSuccessors[i] != NULL) BitSetTester::testIterator(_componentSuccessors[i], false); }
Implements TransitiveClosureAlgorithm.
Definition at line 464 of file PWAHStackTC.cpp.
References BitSetIterator::next().
template<class B> long PWAHStackTC< B >::countTotalNumberOfIntervals ()
template<> long PWAHStackTC< IntervalBitSet >::countTotalNumberOfIntervals ()
Definition at line 702 of file PWAHStackTC.cpp.
template<class B > void PWAHStackTC< B >::dfsVisit (unsigned int vertexIndex) private
Definition at line 84 of file PWAHStackTC.cpp.
template<class B > int PWAHStackTC< B >::getNumberOfComponents () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 770 of file PWAHStackTC.cpp.
template<class B > string PWAHStackTC< B >::getStatistics () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 698 of file PWAHStackTC.cpp.
template<> string PWAHStackTC< IntervalBitSet >::getStatistics () virtual
ss << "Number of edges: " << _graph->countNumberOfEdges() << endl; ss << "Number of strongly connected components: " << _componentSizes.size() << endl; ss << "Number of bits required to store all WAH bitsets: " << this->memoryUsedByBitSets() << endl;
Implements TransitiveClosureAlgorithm.
Definition at line 741 of file PWAHStackTC.cpp.
template<class B > long PWAHStackTC< B >::memoryUsedByBitSets () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 685 of file PWAHStackTC.cpp.
template<class B > long PWAHStackTC< B >::memoryUsedByIntervalLists () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 774 of file PWAHStackTC.cpp.
References IntervalBitSet::copy(), and IntervalBitSet::memoryUsage().
template<class B > bool PWAHStackTC< B >::reachable (unsigned int src, unsigned int dst) virtual
Answers a reachability query for two vertices 'src' and 'dst'.
Implements TransitiveClosureAlgorithm.
Definition at line 658 of file PWAHStackTC.cpp.
Referenced by doSourcesTargetsReachability().
template<class B> void PWAHStackTC< B >::reachablepairs (vector< unsigned int > & sources, vector< unsigned int > & targets, vector< vector< unsigned int > > & reachable_pairs)
Referenced by doSourcesTargetsReachability().
template<> void PWAHStackTC< PWAHBitSet< 8 > >::reachablepairs (vector< unsigned int > & sources, vector< unsigned int > & targets, vector< vector< unsigned int > > & reachable)
Determines for each possible source/target pair whether they are reachable or not. Returns the number or pairs that were reachable and stores the result in the reachable vector.
This implementation is more efficient than actually doing individual queries using "reachable", as it will only iterate over the reachability PWAHBitSet for components once (so if multiple sources are in the same strongly connected component, this saves time), and it will iterate over the PWAHBitSet to determine the reachability of each target.
Result stored in reachable: reachable[si1] = { t1, t2, t3, tn }
Where
si1 is the index of the source vertex in the sources vector (i.e., si1 is not a vertex index itself!)
t1, ..., tn are the reachable target vertices (i.e., t1 is a vertex index of the target vertex)
Note that reachable_pairs is a vector of pointers to vectors {t1, ..., tn} : if source vertices share the same strongly connected component, they wil also share the same vector {t1, ..., tn}
The calling method is responsible for freeing the memory in the reachable array!
Definition at line 543 of file PWAHStackTC.cpp.
template<class B > string PWAHStackTC< B >::tcToString () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 344 of file PWAHStackTC.cpp.
References BitSet::get().
template<class B > long PWAHStackTC< B >::totalMemoryUsage () virtual
Implements TransitiveClosureAlgorithm.
Definition at line 693 of file PWAHStackTC.cpp.
template<class B > void PWAHStackTC< B >::writeToChacoFile (string filename) virtual
Stores the transitive closure in a Chaco-formatted file. Can be huge!
Implements TransitiveClosureAlgorithm.
Definition at line 766 of file PWAHStackTC.cpp.
Friends And Related Function Documentation
template<class B> friend class BitSetTester< IntervalBitSet > friend
Definition at line 88 of file PWAHStackTC.h.
template<class B> friend class BitSetTester< PWAHBitSet< 2 > > friend
Definition at line 90 of file PWAHStackTC.h.
template<class B> friend class BitSetTester< PWAHBitSet< 4 > > friend
Definition at line 91 of file PWAHStackTC.h.
template<class B> friend class BitSetTester< PWAHBitSet< 8 > > friend
Definition at line 92 of file PWAHStackTC.h.
template<class B> friend class BitSetTester< WAHBitSet > friend
Definition at line 89 of file PWAHStackTC.h.
Member Data Documentation
template<class B> vector<unsigned int> PWAHStackTC< B >::_componentSizes private
Definition at line 45 of file PWAHStackTC.h.
template<class B> vector<B*> PWAHStackTC< B >::_componentSuccessors private
Definition at line 40 of file PWAHStackTC.h.
template<class B> vector<int*> PWAHStackTC< B >::_componentVertices private
Definition at line 44 of file PWAHStackTC.h.
template<class B> DynamicStack* PWAHStackTC< B >::_cStack private
Definition at line 48 of file PWAHStackTC.h.
template<class B> Graph* PWAHStackTC< B >::_graph private
Definition at line 39 of file PWAHStackTC.h.
template<class B> int PWAHStackTC< B >::_lastComponentIndex private
Definition at line 55 of file PWAHStackTC.h.
template<class B> int PWAHStackTC< B >::_lastDFSSeqNo private
Definition at line 54 of file PWAHStackTC.h.
template<class B> PerformanceTimer PWAHStackTC< B >::_mergeTimer private
Definition at line 58 of file PWAHStackTC.h.
template<class B> int PWAHStackTC< B >::_minOutDegreeForMultiOR private
Definition at line 57 of file PWAHStackTC.h.
template<class B> bool PWAHStackTC< B >::_reflexitive private
Definition at line 56 of file PWAHStackTC.h.
template<class B> unsigned int* PWAHStackTC< B >::_savedCStackSize private
Definition at line 50 of file PWAHStackTC.h.
template<class B> unsigned int* PWAHStackTC< B >::_savedVStackSize private
Definition at line 49 of file PWAHStackTC.h.
template<class B> bool PWAHStackTC< B >::_storeComponentVertices private
Definition at line 43 of file PWAHStackTC.h.
template<class B> unsigned int* PWAHStackTC< B >::_vertexCandidateComponentRoot private
Definition at line 51 of file PWAHStackTC.h.
template<class B> int* PWAHStackTC< B >::_vertexComponents private
Definition at line 42 of file PWAHStackTC.h.
template<class B> int* PWAHStackTC< B >::_vertexDFSSeqNo private
Definition at line 53 of file PWAHStackTC.h.
template<class B> StaticBitSet* PWAHStackTC< B >::_vertexSelfLoop private
Definition at line 52 of file PWAHStackTC.h.
template<class B> DynamicBitSet PWAHStackTC< B >::_visited private
Definition at line 46 of file PWAHStackTC.h.
template<class B> DynamicStack* PWAHStackTC< B >::_vStack private
Definition at line 47 of file PWAHStackTC.h.
The documentation for this class was generated from the following files:
src/algorithms/PWAHStackTC.h
src/algorithms/PWAHStackTC.cpp