PWAHStackTC: Graph Class Reference
Graph Class Reference
#include <Graph.h>
Public Member Functions
Graph ()
virtual ~Graph ()
unsigned int getNumberOfVertices ()
unsigned int countNumberOfEdges ()
float computeAvgOutDegree ()
int computeMaxOutDegree ()
int findMaxOutDegreeVertex ()
int computeMinOutDegree ()
int findMinOutDegreeVertex ()
double computeAverageLocalClusteringCoefficient ()
double computeLocalClusteringCoefficient (int vertexIndex)
int computeMaxInDegree ()
int findMaxInDegreeVertex ()
float computeAvgInDegree ()
int computeMinInDegree ()
int findMinInDegreeVertex ()
unsigned int vertexInDegree (int v)
vector< int > * getChildren (unsigned int vertexIndex)
Static Public Member Functions
static Graph parseChacoFile (string filename)
static vector< string > split (const string &s, char delim)
static vector< string > & split (const string &s, char delim, vector< string > &elems)
Private Attributes
vector< vector< int > > _vertices
vector< int > _vertexIndegree
Detailed Description
Definition at line 26 of file Graph.h.
Constructor & Destructor Documentation
Graph::Graph ()
Definition at line 32 of file Graph.cpp.
Graph::~Graph () virtual
Definition at line 33 of file Graph.cpp.
Member Function Documentation
double Graph::computeAverageLocalClusteringCoefficient ()
Definition at line 95 of file Graph.cpp.
float Graph::computeAvgInDegree ()
Definition at line 128 of file Graph.cpp.
float Graph::computeAvgOutDegree ()
Definition at line 120 of file Graph.cpp.
double Graph::computeLocalClusteringCoefficient (int vertexIndex)
Definition at line 51 of file Graph.cpp.
References StaticBitSet::get(), and StaticBitSet::set().
int Graph::computeMaxInDegree ()
Definition at line 217 of file Graph.cpp.
int Graph::computeMaxOutDegree ()
Definition at line 210 of file Graph.cpp.
int Graph::computeMinInDegree ()
Definition at line 178 of file Graph.cpp.
int Graph::computeMinOutDegree ()
Definition at line 203 of file Graph.cpp.
unsigned int Graph::countNumberOfEdges ()
Definition at line 43 of file Graph.cpp.
Referenced by main().
int Graph::findMaxInDegreeVertex ()
Definition at line 185 of file Graph.cpp.
int Graph::findMaxOutDegreeVertex ()
Definition at line 136 of file Graph.cpp.
int Graph::findMinInDegreeVertex ()
Definition at line 164 of file Graph.cpp.
int Graph::findMinOutDegreeVertex ()
Definition at line 150 of file Graph.cpp.
vector< int > * Graph::getChildren (unsigned int vertexIndex)
Definition at line 39 of file Graph.cpp.
unsigned int Graph::getNumberOfVertices ()
Definition at line 35 of file Graph.cpp.
Referenced by doSourcesTargetsReachability(), and main().
Graph Graph::parseChacoFile (string filename) static
Definition at line 224 of file Graph.cpp.
References _vertexIndegree, and _vertices.
Referenced by doSourcesTargetsReachability(), main(), and Validator::validate().
vector< string > Graph::split (const string & s, char delim) static
Definition at line 115 of file Graph.cpp.
vector< string > & Graph::split (const string & s, char delim, vector< string > & elems) static
Definition at line 106 of file Graph.cpp.
unsigned int Graph::vertexInDegree (int v)
Definition at line 199 of file Graph.cpp.
Member Data Documentation
vector<int> Graph::_vertexIndegree private
Definition at line 29 of file Graph.h.
Referenced by parseChacoFile().
vector<vector<int> > Graph::_vertices private
Definition at line 28 of file Graph.h.
Referenced by parseChacoFile().
The documentation for this class was generated from the following files:
src/datastructures/Graph.h
src/datastructures/Graph.cpp