PWAHStackTC: PerformanceTimer Class Reference
PerformanceTimer Class Reference
#include <PerformanceTimer.h>
Public Member Functions
PerformanceTimer ()
virtual ~PerformanceTimer ()
double reset ()
double resetAndStop ()
double currRunTime ()
long currRunTimeMicro ()
void pause ()
void resume ()
bool running ()
Static Public Member Functions
static PerformanceTimer start ()
static double diffTimeMilliSecs (const timeval *time1, const timeval *time2)
static long diffTimeMicroSecs (const timeval *time1, const timeval *time2)
static long currTimeMilliSecs ()
Private Attributes
struct timeval * _startTime
double _storedRunTime
Detailed Description
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 25 of file PerformanceTimer.h.
Constructor & Destructor Documentation
PerformanceTimer::PerformanceTimer ()
Definition at line 26 of file PerformanceTimer.cpp.
PerformanceTimer::~PerformanceTimer () virtual
Definition at line 31 of file PerformanceTimer.cpp.
Member Function Documentation
double PerformanceTimer::currRunTime ()
Definition at line 68 of file PerformanceTimer.cpp.
Referenced by doSourcesTargetsReachability().
long PerformanceTimer::currRunTimeMicro ()
Definition at line 86 of file PerformanceTimer.cpp.
Referenced by doSourcesTargetsReachability().
long PerformanceTimer::currTimeMilliSecs () static
Definition at line 80 of file PerformanceTimer.cpp.
long PerformanceTimer::diffTimeMicroSecs (const timeval * time1, const timeval * time2) static
Definition at line 62 of file PerformanceTimer.cpp.
double PerformanceTimer::diffTimeMilliSecs (const timeval * time1, const timeval * time2) static
Definition at line 56 of file PerformanceTimer.cpp.
void PerformanceTimer::pause ()
Definition at line 98 of file PerformanceTimer.cpp.
double PerformanceTimer::reset ()
Definition at line 41 of file PerformanceTimer.cpp.
Referenced by doSourcesTargetsReachability(), main(), and Validator::validate().
double PerformanceTimer::resetAndStop ()
Definition at line 48 of file PerformanceTimer.cpp.
void PerformanceTimer::resume ()
Definition at line 106 of file PerformanceTimer.cpp.
Referenced by start().
bool PerformanceTimer::running ()
Definition at line 112 of file PerformanceTimer.cpp.
PerformanceTimer PerformanceTimer::start () static
Definition at line 35 of file PerformanceTimer.cpp.
References resume().
Referenced by main().
Member Data Documentation
struct timeval* PerformanceTimer::_startTime private
Definition at line 27 of file PerformanceTimer.h.
double PerformanceTimer::_storedRunTime private
Definition at line 28 of file PerformanceTimer.h.
The documentation for this class was generated from the following files:
src/util/PerformanceTimer.h
src/util/PerformanceTimer.cpp