PWAHStackTC: WAHBitSet Class Reference
WAHBitSet Class Reference
#include <WAHBitSet.h>
Public Member Functions
WAHBitSet (DynamicBitSet *dynamicBitSet)
WAHBitSet ()
virtual ~WAHBitSet ()
void setBits (int blockSeq, int value)
void set (unsigned int bitIndex)
void set (unsigned int bitIndex, bool value)
const bool get (unsigned int bitIndex)
const string toString ()
const unsigned int size ()
bool isEmpty ()
void clear ()
const int blocksize ()
BitSetIterator * iterator ()
long memoryUsage ()
string bsImplementationName ()
Public Member Functions inherited from BitSet
BitSet ()
virtual ~BitSet ()
virtual const bool equals (BitSet *otherBitSet)
Static Public Member Functions
static int generateRandomLiteralBlock ()
static string toBitString (int value)
static WAHBitSet * constructByOr (const WAHBitSet *first, const WAHBitSet *second)
static void multiOr (WAHBitSet **bitSets, unsigned int numBitSets, WAHBitSet *result)
Merges multiple WAHBitSet objects into a single WAHBitSet by computing the logical OR.
Static Public Attributes
static const bool DEBUGGING = false
static const unsigned int WORDSIZE = 32
static const unsigned int BLOCKSIZE = WORDSIZE - 1
static const int MAX_BLOCKS_IN_FILL = 1073741823
static const int BLOCK_ONES = 0b01111111111111111111111111111111
static const int BLOCK_ZEROES = 0b00000000000000000000000000000000
static const int EMPTY_ONEFILL = 0b11000000000000000000000000000000
static const int EMPTY_ZEROFILL = 0b10000000000000000000000000000000
static const int SIMPLE_ONEFILL = 0b11000000000000000000000000000001
static const int SIMPLE_ZEROFILL = 0b10000000000000000000000000000001
Private Member Functions
void addOneFill (int numBlocks)
void addZeroFill (int numBlocks)
void addLiteral (int value)
void init ()
void decompressLastWord ()
Private Attributes
int _lastBitIndex
vector< int > _compressedBits
int _plainWord
int _plainWordBlockSeq
bool _empty
Friends
class WAHBitSetIterator
class WAHBitSetTester
class BitSetTester< WAHBitSet >
Detailed Description
Definition at line 30 of file WAHBitSet.h.
Constructor & Destructor Documentation
WAHBitSet::WAHBitSet (DynamicBitSet * dynamicBitSet)
Definition at line 41 of file WAHBitSet.cpp.
References DynamicBitSet::get(), and DynamicBitSet::size().
WAHBitSet::WAHBitSet ()
Definition at line 34 of file WAHBitSet.cpp.
WAHBitSet::~WAHBitSet () virtual
Definition at line 38 of file WAHBitSet.cpp.
Member Function Documentation
void WAHBitSet::addLiteral (int value) private
Definition at line 238 of file WAHBitSet.cpp.
References IS_LITERAL_ONEFILL, and IS_LITERAL_ZEROFILL.
Referenced by constructByOr(), and multiOr().
void WAHBitSet::addOneFill (int numBlocks) private
Definition at line 196 of file WAHBitSet.cpp.
References FILL_LENGTH, and IS_ONEFILL.
Referenced by constructByOr(), and multiOr().
void WAHBitSet::addZeroFill (int numBlocks) private
Definition at line 217 of file WAHBitSet.cpp.
References FILL_LENGTH, and IS_ZEROFILL.
Referenced by constructByOr(), and multiOr().
const int WAHBitSet::blocksize () virtual
Implements BitSet.
Definition at line 788 of file WAHBitSet.cpp.
string WAHBitSet::bsImplementationName () virtual
Implements BitSet.
Definition at line 792 of file WAHBitSet.cpp.
void WAHBitSet::clear () virtual
Implements BitSet.
Definition at line 192 of file WAHBitSet.cpp.
WAHBitSet * WAHBitSet::constructByOr (const WAHBitSet * first, const WAHBitSet * second) static
Definition at line 264 of file WAHBitSet.cpp.
References _compressedBits, _lastBitIndex, _plainWord, addLiteral(), addOneFill(), addZeroFill(), decompressLastWord(), FILL_LENGTH, IS_FILL, and IS_ONEFILL.
void WAHBitSet::decompressLastWord () private
Definition at line 745 of file WAHBitSet.cpp.
References FILL_LENGTH, IS_FILL, IS_ONEFILL, LITERAL_ONEFILL, and LITERAL_ZEROFILL.
Referenced by constructByOr(), and multiOr().
int WAHBitSet::generateRandomLiteralBlock () static
Generates 31 random bits which cannot be represented as a 0-fill or 1-fill.
Definition at line 253 of file WAHBitSet.cpp.
References I_SET_BIT, and RAND_FLOAT.
const bool WAHBitSet::get (unsigned int bitIndex) virtual
Implements BitSet.
Definition at line 118 of file WAHBitSet.cpp.
References FILL_LENGTH, I_GET_BIT, IS_FILL, and IS_ONEFILL.
void WAHBitSet::init () private
Definition at line 50 of file WAHBitSet.cpp.
bool WAHBitSet::isEmpty ()
Definition at line 770 of file WAHBitSet.cpp.
BitSetIterator * WAHBitSet::iterator () virtual
Implements BitSet.
Definition at line 796 of file WAHBitSet.cpp.
long WAHBitSet::memoryUsage ()
Reports the number of bits used to represent this BitSet. This includes the bits used to store the last plain word, but not the bits in bookkeeping variables
Definition at line 782 of file WAHBitSet.cpp.
void WAHBitSet::multiOr (WAHBitSet ** bitSets, unsigned int numBitSets, WAHBitSet * result) static
Merges multiple WAHBitSet objects into a single WAHBitSet by computing the logical OR.
Parameters
bitSets the source WAHBitSet objects
numBitSets the number of source WAHBitSet objects
result pointer to a WAHBitSet to store the result of the logical OR
Definition at line 564 of file WAHBitSet.cpp.
References _compressedBits, _lastBitIndex, _plainWord, addLiteral(), addOneFill(), addZeroFill(), decompressLastWord(), FILL_LENGTH, IS_FILL, IS_ONEFILL, IS_ZEROFILL, and size().
void WAHBitSet::set (unsigned int bitIndex) virtual
Reimplemented from BitSet.
Definition at line 46 of file WAHBitSet.cpp.
void WAHBitSet::set (unsigned int bitIndex, bool value) virtual
Implements BitSet.
Definition at line 58 of file WAHBitSet.cpp.
References I_CLEAR_BIT, and I_SET_BIT.
void WAHBitSet::setBits (int blockSeq, int value)
const unsigned int WAHBitSet::size () virtual
Implements BitSet.
Definition at line 774 of file WAHBitSet.cpp.
Referenced by multiOr().
string WAHBitSet::toBitString (int value) static
Definition at line 165 of file WAHBitSet.cpp.
References I_GET_BIT.
const string WAHBitSet::toString () virtual
Reimplemented from BitSet.
Definition at line 176 of file WAHBitSet.cpp.
Friends And Related Function Documentation
friend class BitSetTester< WAHBitSet > friend
Definition at line 98 of file WAHBitSet.h.
friend class WAHBitSetIterator friend
Definition at line 96 of file WAHBitSet.h.
friend class WAHBitSetTester friend
Definition at line 97 of file WAHBitSet.h.
Member Data Documentation
vector<int> WAHBitSet::_compressedBits private
Definition at line 33 of file WAHBitSet.h.
Referenced by constructByOr(), and multiOr().
bool WAHBitSet::_empty private
Definition at line 36 of file WAHBitSet.h.
int WAHBitSet::_lastBitIndex private
Definition at line 32 of file WAHBitSet.h.
Referenced by constructByOr(), and multiOr().
int WAHBitSet::_plainWord private
Definition at line 34 of file WAHBitSet.h.
Referenced by constructByOr(), and multiOr().
int WAHBitSet::_plainWordBlockSeq private
Definition at line 35 of file WAHBitSet.h.
const int WAHBitSet::BLOCK_ONES = 0b01111111111111111111111111111111 static
Definition at line 54 of file WAHBitSet.h.
const int WAHBitSet::BLOCK_ZEROES = 0b00000000000000000000000000000000 static
Definition at line 57 of file WAHBitSet.h.
const unsigned int WAHBitSet::BLOCKSIZE = WORDSIZE - 1 static
Definition at line 47 of file WAHBitSet.h.
Referenced by WAHBitSetIterator::next().
const bool WAHBitSet::DEBUGGING = false static
Definition at line 45 of file WAHBitSet.h.
const int WAHBitSet::EMPTY_ONEFILL = 0b11000000000000000000000000000000 static
Definition at line 60 of file WAHBitSet.h.
const int WAHBitSet::EMPTY_ZEROFILL = 0b10000000000000000000000000000000 static
Definition at line 63 of file WAHBitSet.h.
const int WAHBitSet::MAX_BLOCKS_IN_FILL = 1073741823 static
Definition at line 50 of file WAHBitSet.h.
const int WAHBitSet::SIMPLE_ONEFILL = 0b11000000000000000000000000000001 static
Definition at line 66 of file WAHBitSet.h.
const int WAHBitSet::SIMPLE_ZEROFILL = 0b10000000000000000000000000000001 static
Definition at line 69 of file WAHBitSet.h.
const unsigned int WAHBitSet::WORDSIZE = 32 static
Definition at line 46 of file WAHBitSet.h.
The documentation for this class was generated from the following files:
src/datastructures/bitsets/wah/WAHBitSet.h
src/datastructures/bitsets/wah/WAHBitSet.cpp