PWAHStackTC: Validator Class Reference
Validator Class Reference
#include <Validator.h>
Public Member Functions
Validator ()
virtual ~Validator ()
Static Public Member Functions
static void validate ()
Detailed Description
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 24 of file Validator.h.
Constructor & Destructor Documentation
Validator::Validator ()
Definition at line 34 of file Validator.cpp.
Validator::~Validator () virtual
Definition at line 35 of file Validator.cpp.
Member Function Documentation
void Validator::validate () static
Definition at line 37 of file Validator.cpp.
References TransitiveClosureAlgorithm::algorithmName(), TransitiveClosureAlgorithm::computeTransitiveClosure(), TransitiveClosureAlgorithm::countNumberOfEdgesInTC(), TransitiveClosureAlgorithm::memoryUsedByBitSets(), Graph::parseChacoFile(), and PerformanceTimer::reset().
Referenced by runValidatorWhenRequested().
The documentation for this class was generated from the following files:
src/util/Validator.h
src/util/Validator.cpp