PWAHStackTC: PWAHBitSet< P > Class Template Reference
PWAHBitSet< P > Class Template Reference
#include <PWAHBitSet.h>
Public Member Functions
PWAHBitSet ()
virtual ~PWAHBitSet ()
void set (unsigned int bitIndex)
Sets the bit with index 'bitIndex' in this PWAHBitSet to '1'.
void set (unsigned int bitIndex, bool value)
void clear ()
const bool get (unsigned int bitIndex, bool disableIndex)
Determines whether the bit at the given index is set.
const bool get (unsigned int bitIndex)
Returns the value (true/false <–> 1/0) of the bit at index 'bitIndex'.
const bool incr_get (unsigned int bitIndex)
Same as PWAHBitSet::get(unsigned int, bool), but implements an optimisation to support incremental gets (i.e., to get multiple bits in an efficient way, but the queried bits need to be queried incrementally).
void reset_incr_get_indices ()
Resets the indices used for the 'incr_get' method.
const unsigned int size ()
const long memoryUsage ()
string bsImplementationName ()
BitSetIterator * iterator ()
const string toString ()
const int blocksize ()
template<>
long fill_length (long bits, unsigned short partitionIndex)
template<>
long fill_length (long bits, unsigned short partitionIndex)
template<>
long fill_length (long bits, unsigned short partitionIndex)
template<>
long fill_length (long bits, unsigned short partitionIndex)
template<>
string bsImplementationName ()
template<>
string bsImplementationName ()
template<>
string bsImplementationName ()
template<>
string bsImplementationName ()
Public Member Functions inherited from BitSet
BitSet ()
virtual ~BitSet ()
virtual const bool equals (BitSet *otherBitSet)
Static Public Member Functions
static void multiOr (PWAHBitSet **bitSets, unsigned int numBitSets, PWAHBitSet *result)
Merges multiple WAHBitSet objects into a single WAHBitSet by computing the logical OR.
static PWAHBitSet * constructByOr (const PWAHBitSet *first, const PWAHBitSet *second)
static string toBitString (long value)
static long fill_length (long bits, unsigned short partitionIndex)
static void setIndexChunkSize (int chunkSize)
Private Member Functions
unsigned int _bit_block_index (unsigned int bitIndex)
void compressPlainPartition ()
Compress the uncompressed bits in the plain partition.
void popLastPartition ()
Removes the last partition. This will effectively remove one or more blocks.
void addFill (bool oneFill, int numBlocks, int firstBlockIndex)
Adds a partition containing a fill (type is indicated by boolean parameter 'oneFill') of size 'numBlocks' to the compressed words. Might the last partition contain a fill of equal type, this existing fill is extended.
void addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex)
void addLiteral (long value, int blockIndex)
void addFillPartition (bool oneFill, long numBlocks, int firstBlockIndex)
void addPartition (bool isFill, long value)
Takes the first _blockSize bits from the given value and adds these as a new partition to the vector with compressed bits.
void decompressLastBlock ()
void updateIndex (int numBlocks, int firstBlockIndex)
void setIndexEntry (unsigned int chunkIndex, int indexWord, int indexPartition, int indexPartitionOffset)
int countNumberOfBlocks ()
Performs a count of the number of blocks in this PWAHBitSet.
const bool _get (unsigned int bitIndex, bool disableIndex, unsigned int initialWordIndex, unsigned int initialPartitionIndex, long initialBlockIndex, bool update_incr_get_indices)
Determines whether the bit at the given index is set, which starts scanning at the provided indices.
template<>
int _indexChunkSize
template<>
int _indexChunkSize
template<>
int _indexChunkSize
template<>
int _indexChunkSize
template<>
const int _partitionOffsets [1]
template<>
const int _partitionOffsets [2]
template<>
const int _partitionOffsets [4]
template<>
const int _partitionOffsets [8]
template<>
const int _blockSize
template<>
const int _blockSize
template<>
const int _blockSize
template<>
const int _blockSize
template<>
const long _maxBlocksPerFill
template<>
const long _maxBlocksPerFill
template<>
const long _maxBlocksPerFill
template<>
const long _maxBlocksPerFill
template<>
bool is_fill (long bits, unsigned short partitionIndex)
template<>
bool is_fill (long bits, unsigned short partitionIndex)
template<>
bool is_fill (long bits, unsigned short partitionIndex)
template<>
bool is_fill (long bits, unsigned short partitionIndex)
template<>
bool is_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_onefill (long bits, unsigned short partitionIndex)
template<>
long extract_partition (long word, unsigned short partitionIndex)
template<>
long extract_partition (long word, unsigned short partitionIndex)
template<>
long extract_partition (long word, unsigned short partitionIndex)
template<>
long extract_partition (long word, unsigned short partitionIndex)
template<>
long clear_partition (long word, unsigned short partitionIndex)
template<>
long clear_partition (long word, unsigned short partitionIndex)
template<>
long clear_partition (long word, unsigned short partitionIndex)
template<>
long clear_partition (long word, unsigned short partitionIndex)
template<>
short blocks_num_partitions (int numBlocks)
template<>
short blocks_num_partitions (int numBlocks)
template<>
short blocks_num_partitions (int numBlocks)
template<>
short blocks_num_partitions (int numBlocks)
template<>
bool is_literal_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_onefill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_zerofill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_zerofill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_zerofill (long bits, unsigned short partitionIndex)
template<>
bool is_literal_zerofill (long bits, unsigned short partitionIndex)
template<>
void addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex)
template<>
void addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex)
template<>
void addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex)
template<>
void addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex)
Static Private Member Functions
static bool is_fill (long bits, unsigned short partitionIndex)
static bool is_onefill (long bits, unsigned short partitionIndex)
static bool is_zerofill (long bits, unsigned short partitionIndex)
Checks whether the partition with index 'partitionIndex' within 'bits' consists of a 0-fill.
static bool is_literal (long bits, unsigned short partitionIndex)
Checks whether the partition with index 'partitionIndex' within 'bits' consists of literal.
static bool is_literal_onefill (long bits, unsigned short partitionIndex)
static bool is_literal_zerofill (long bits, unsigned short partitionIndex)
static long extract_partition (long bits, unsigned short partitionIndex)
static long clear_partition (long bits, unsigned short partitionIndex)
static short blocks_num_partitions (int numBlocks)
Private Attributes
long _plainBlockIndex
long _lastBitIndex
unsigned short _lastUsedPartition
vector< long > _words
vector< int > _indexWord
vector< unsigned short > _indexPartition
vector< int > _indexPartitionOffset
unsigned int _incr_get_WordIndex
unsigned int _incr_get_PartitionIndex
long _incr_get_BlockIndex
Static Private Attributes
static const long _maxBlocksPerFill
static const int _blockSize
static const int _partitionOffsets [P]
static const bool _VERIFY = false
static int _indexChunkSize
Friends
class PWAHBitSetIterator< P >
class BitSetTester< PWAHBitSet< P > >
Detailed Description
template<unsigned int P>
class PWAHBitSet< P >
Definition at line 32 of file PWAHBitSet.h.
Constructor & Destructor Documentation
template<unsigned int P> PWAHBitSet< P >::PWAHBitSet ()
Constructor for PWAHBitSet
Definition at line 530 of file PWAHBitSet.cpp.
template<unsigned int P> virtual PWAHBitSet< P >::~PWAHBitSet () inline virtual
Definition at line 35 of file PWAHBitSet.h.
Member Function Documentation
template<unsigned int P> unsigned int PWAHBitSet< P >::_bit_block_index (unsigned int bitIndex) inline private
Definition at line 102 of file PWAHBitSet.h.
template<> const int PWAHBitSet< 1 >::_blockSize () private
Define the block size for every possible number of partitions
Definition at line 51 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 2 >::_blockSize () private
Definition at line 52 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 4 >::_blockSize () private
Definition at line 53 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 8 >::_blockSize () private
Definition at line 54 of file PWAHBitSet.cpp.
template<unsigned int P> const bool PWAHBitSet< P >::_get (unsigned int bitIndex, bool disableIndex, unsigned int initialWordIndex, unsigned int initialPartitionIndex, long initialBlockIndex, bool update_incr_get_indices) private
Determines whether the bit at the given index is set, which starts scanning at the provided indices.
This operation takes O(n) times on PWAHBitSet instances without index, or O(k) time on indexes PWAHBitSet instances (k denotes the index granularity)
Parameters
bitIndex the index of the desired bit
disableIndex when true, prevents the 'get' method from using the search index
initialWordIndex the word to start scanning at
initialPartitionIndex the partition of the word to start scanning at
initialBlockIndex the block at the given word/partition
update_incr_get_indices determines whether get will update the _incr_get* values for incremental getting.
Definition at line 654 of file PWAHBitSet.cpp.
References L_GET_BIT.
template<> int PWAHBitSet< 1 >::_indexChunkSize () private
Default: don't use indices
Definition at line 35 of file PWAHBitSet.cpp.
template<> int PWAHBitSet< 2 >::_indexChunkSize () private
Definition at line 36 of file PWAHBitSet.cpp.
template<> int PWAHBitSet< 4 >::_indexChunkSize () private
Definition at line 37 of file PWAHBitSet.cpp.
template<> int PWAHBitSet< 8 >::_indexChunkSize () private
Definition at line 38 of file PWAHBitSet.cpp.
template<> const long PWAHBitSet< 1 >::_maxBlocksPerFill () private
Define the maximum number of blocks a fill can contain for every possible number of partitions
Definition at line 59 of file PWAHBitSet.cpp.
template<> const long PWAHBitSet< 2 >::_maxBlocksPerFill () private
Definition at line 60 of file PWAHBitSet.cpp.
template<> const long PWAHBitSet< 4 >::_maxBlocksPerFill () private
Definition at line 61 of file PWAHBitSet.cpp.
template<> const long PWAHBitSet< 8 >::_maxBlocksPerFill () private
Definition at line 62 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 1 >::_partitionOffsets () private
Define the offset of partitions within the 64 bit word.
Definition at line 43 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 2 >::_partitionOffsets () private
Definition at line 44 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 4 >::_partitionOffsets () private
Definition at line 45 of file PWAHBitSet.cpp.
template<> const int PWAHBitSet< 8 >::_partitionOffsets () private
Definition at line 46 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex) private
template<> void PWAHBitSet< 1 >::addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex) private
This method does not extend existing fills and should not be called directly, but only through addFill(...). Furthermore, this method assumes that at least two partitions of the current word are unused
Definition at line 1669 of file PWAHBitSet.cpp.
template<> void PWAHBitSet< 2 >::addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex) private
Definition at line 1672 of file PWAHBitSet.cpp.
template<> void PWAHBitSet< 4 >::addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex) private
Note that the PWAHBitSet<4> is only capable of storing an extended fill covering 2 or 3 partitions. Would an extended fill require 4 partitions, an integer overflow for the 'numBlocks' parameter would have occurred.
Explanation of what's going on below:
Suppose a 1-fill of length 70,000 blocks is to be added. In binary notation, that plain number (just the number) would be stored as: 0b10001000101110000
In this PWAHBitSet<4>, the block size equals 15. That means 14 bits are available to store a fill length. Therefore, we'll have to cut the 70,000 in two pieces. Furthermore, a 1-bit should be added to indicate the fact this fill represents a sequence of 1-bits.
The result should equal two partitions of 15 bits, each starting with a 1-bit to indicate the 1-fill:
first partition: 0b101000101110000 second partition: 0b100000000000100
Compare the result with the original number: second & first partition: 0b100000000000100|101000101110000 original number: 0b000000000000100|x01000101110000
The first partition contains the first 14 bits of the original fill length, prepended by a 1-bit. The second partition contains the remaining 3 bits of the original fill length, again prepended by a 1-bit.
Note that this example only covers the case in which a fill covers 2 partitions. Obviously, it is possible for a fill to cover 3 partitions. However, a fill covering 4 partitions would have yielded an integer overflow in the 'numBlocks' parameter.
Definition at line 1675 of file PWAHBitSet.cpp.
template<> void PWAHBitSet< 8 >::addExtendedFillPartitions (bool oneFill, int numBlocks, int firstBlockIndex) private
Definition at line 1791 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::addFill (bool oneFill, int numBlocks, int firstBlockIndex) private
Adds a partition containing a fill (type is indicated by boolean parameter 'oneFill') of size 'numBlocks' to the compressed words. Might the last partition contain a fill of equal type, this existing fill is extended.
Definition at line 883 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> void PWAHBitSet< P >::addFillPartition (bool oneFill, long numBlocks, int firstBlockIndex) private
Definition at line 967 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::addLiteral (long value, int blockIndex) private
Definition at line 956 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> void PWAHBitSet< P >::addPartition (bool isFill, long value) private
Takes the first _blockSize bits from the given value and adds these as a new partition to the vector with compressed bits.
Example for the PWAHBitSet<4> case:
each long word on vector<long> _compressedWords consists of 5 parts:
bits 63-60: 4 bits header, indicating whether each of the 4 partitions is a fill or literal (0 = literal, 1 = fill)
bits 59-45: 15 bits partition 3
bits 44-30: 15 bits partition 2
bits 29-15: 15 bits partition 1
bits 14-0: 15 bits partition 0
a partition can contain:
a literal block of 15 bits
a fill block. The first bit indicates 0/1 fill, the other 14 bits indicate the fill length (max. fill length = 2^14 = 16,384 blocks = 245,760 bits)
The 'isFill' parameter tells this method to set the header bit of the partition to either 0 (literal, isFill = false) or 1 (fill, isFill = true)
The 'value' parameter of this method is a long, formatted as follows (X and Y denote real values, 0-bits indicate bits that will be ignored):
PWAHBitSet<1>: 63 bits: 0b0YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PWAHBitSet<2>: 31 bits: 0b000000000000000000000000000000000YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PWAHBitSet<4>: 15 bits: 0b0000000000000000000000000000000000000000000000000YXXXXXXXXXXXXXX
PWAHBitSet<8>: 7 bits: 0b000000000000000000000000000000000000000000000000000000000YXXXXXX
These n bits are the exact value of the partition. For a fill partition, the first bit (denoted using an 'Y' in the example above) should indicate the fill type (0-fill or 1-fill). For a literal partition, all n bits (both X and Y) may be used to indicate values of literal bits.
Note that all bits denoted with an underscore are ignored!
Definition at line 1116 of file PWAHBitSet.cpp.
References L_SET_BIT.
template<unsigned int P> static short PWAHBitSet< P >::blocks_num_partitions (int numBlocks) static private
Referenced by PWAHBitSetIterator< P >::next().
template<> short PWAHBitSet< 8 >::blocks_num_partitions (int numBlocks) private
Definition at line 214 of file PWAHBitSet.cpp.
template<> short PWAHBitSet< 4 >::blocks_num_partitions (int numBlocks) private
Definition at line 222 of file PWAHBitSet.cpp.
template<> short PWAHBitSet< 2 >::blocks_num_partitions (int numBlocks) private
Definition at line 227 of file PWAHBitSet.cpp.
template<> short PWAHBitSet< 1 >::blocks_num_partitions (int numBlocks) private
Definition at line 230 of file PWAHBitSet.cpp.
template<unsigned int P> const int PWAHBitSet< P >::blocksize () virtual
Implements BitSet.
Definition at line 1640 of file PWAHBitSet.cpp.
template<unsigned int P> string PWAHBitSet< P >::bsImplementationName () virtual
Implements BitSet.
template<> string PWAHBitSet< 1 >::bsImplementationName () virtual
Implements BitSet.
Definition at line 1857 of file PWAHBitSet.cpp.
template<> string PWAHBitSet< 2 >::bsImplementationName () virtual
Implements BitSet.
Definition at line 1864 of file PWAHBitSet.cpp.
template<> string PWAHBitSet< 4 >::bsImplementationName () virtual
Implements BitSet.
Definition at line 1871 of file PWAHBitSet.cpp.
template<> string PWAHBitSet< 8 >::bsImplementationName () virtual
Implements BitSet.
Definition at line 1878 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::clear () virtual
Implements BitSet.
Definition at line 545 of file PWAHBitSet.cpp.
template<unsigned int P> static long PWAHBitSet< P >::clear_partition (long bits, unsigned short partitionIndex) inline static private
template<> long PWAHBitSet< 1 >::clear_partition (long word, unsigned short partitionIndex) inline private
Will not clear the type of the partition (fill / literal) in the header. Ergo, only the bits indicated with 'X' are cleared:
PWAHBitSet<8>: 7 bits, 0b000000000000000000000000000000000000000000000000000000000XXXXXXX; PWAHBitSet<4>: 15 bits, 0b0000000000000000000000000000000000000000000000000XXXXXXXXXXXXXXX; PWAHBitSet<2>: 31 bits, 0b000000000000000000000000000000000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; PWAHBitSet<1>: 63 bits, 0b0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;
Definition at line 186 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 2 >::clear_partition (long word, unsigned short partitionIndex) inline private
Definition at line 189 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 4 >::clear_partition (long word, unsigned short partitionIndex) inline private
Definition at line 193 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 8 >::clear_partition (long word, unsigned short partitionIndex) inline private
Definition at line 199 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::compressPlainPartition () private
Compress the uncompressed bits in the plain partition.
Note that this method does not increase the index _plainBlockIndex! The method will update the value of _lastUsedPartition, though.
Definition at line 833 of file PWAHBitSet.cpp.
template<unsigned int P> PWAHBitSet< P > * PWAHBitSet< P >::constructByOr (const PWAHBitSet< P > * first, const PWAHBitSet< P > * second) static
Definition at line 1622 of file PWAHBitSet.cpp.
template<unsigned int P> int PWAHBitSet< P >::countNumberOfBlocks () private
Performs a count of the number of blocks in this PWAHBitSet.
Only intended for verification purposes!
Definition at line 1498 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> void PWAHBitSet< P >::decompressLastBlock () private
Definition at line 1559 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> static long PWAHBitSet< P >::extract_partition (long bits, unsigned short partitionIndex) inline static private
Referenced by PWAHBitSetIterator< P >::next().
template<> long PWAHBitSet< 1 >::extract_partition (long word, unsigned short partitionIndex) private
Will not return the type of the partition (fill / literal), only its contents. Note that the contents will always reside in the least significant bits of the word
PWAHBitSet<8>: 7 bits, 0b000000000000000000000000000000000000000000000000000000000XXXXXXX; PWAHBitSet<4>: 15 bits, 0b0000000000000000000000000000000000000000000000000XXXXXXXXXXXXXXX; PWAHBitSet<2>: 31 bits, 0b000000000000000000000000000000000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; PWAHBitSet<1>: 63 bits, 0b0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;
Definition at line 159 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 2 >::extract_partition (long word, unsigned short partitionIndex) private
Definition at line 162 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 4 >::extract_partition (long word, unsigned short partitionIndex) private
Definition at line 166 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 8 >::extract_partition (long word, unsigned short partitionIndex) private
Definition at line 170 of file PWAHBitSet.cpp.
template<unsigned int P> static long PWAHBitSet< P >::fill_length (long bits, unsigned short partitionIndex) static
Referenced by PWAHBitSetIterator< P >::next().
template<> long PWAHBitSet< 1 >::fill_length (long bits, unsigned short partitionIndex)
A fill might span multiple partitions, but will never span over two or more words. For example take a look at these two words, compressed using PWAHBitSet<8>:
0b00111111|_______|_______|0000010|1000011|0000101|1010010|1011011|1001001 0b10000000|1010001|_______|.......
The first word consists of: 2 literal partitions, 1 0-fill partition, 1 1-fill partition, 1 0-fill partition, 3 1-fill partitions
The 3 consecutive 1-fill partitions at the end of the first word denote one large 1-fill of length 0b010010011011001001 (= 75,465 blocks). Note that this is NOT equal to 0b010010 + 0b1011011 + 0b1011011.
Also note that the second word contains a 1-fill in the first partition. This 1-fill is stored separate from the extended 1-fill in the first word. Therefore, the total number of adjacent 1-bits which were compressed equals 0b010010011011001001 + 0b1010001 = 75546 blocks = 528,822 bits
(note that this is an arbitrary example, the 528,822 1-bits would have been compressed using 20 bits (3 blocks) in the first partition)
Definition at line 367 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 2 >::fill_length (long bits, unsigned short partitionIndex)
Definition at line 375 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 4 >::fill_length (long bits, unsigned short partitionIndex)
PWAHBitSet<4> case: 4 partitions of 15 bits and a header of 4 bits. An extended fill can not cover multiple words. Therefore, only partitions 0, 1 and 2 can be the first partition of an extended fill. Furthermore, an extended fill will cover at most 3 partitions.
Definition at line 389 of file PWAHBitSet.cpp.
template<> long PWAHBitSet< 8 >::fill_length (long bits, unsigned short partitionIndex)
Definition at line 449 of file PWAHBitSet.cpp.
template<unsigned int P> const bool PWAHBitSet< P >::get (unsigned int bitIndex, bool disableIndex)
Determines whether the bit at the given index is set.
This operation takes O(n) times on PWAHBitSet instances without index, or O(k) time on indexes PWAHBitSet instances (k denotes the index granularity)
Parameters
bitIndex the index of the desired bit
disableIndex when true, prevents the 'get' method from using the search index
Definition at line 606 of file PWAHBitSet.cpp.
template<unsigned int P> const bool PWAHBitSet< P >::get (unsigned int bitIndex) virtual
Returns the value (true/false <–> 1/0) of the bit at index 'bitIndex'.
Complexity: linear in the size of the compressed data.
Parameters
bitIndex the index of the bit to be queried.
Implements BitSet.
Definition at line 566 of file PWAHBitSet.cpp.
template<unsigned int P> const bool PWAHBitSet< P >::incr_get (unsigned int bitIndex)
Same as PWAHBitSet::get(unsigned int, bool), but implements an optimisation to support incremental gets (i.e., to get multiple bits in an efficient way, but the queried bits need to be queried incrementally).
Complexity for a single lookup: O(n) Total complexity for a series of lookups: O(n)
For a series of lookups, this method will only do a single pass over the entire bitset.
Definition at line 592 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 1 >::is_fill (long bits, unsigned short partitionIndex) inline private
Definition at line 71 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 2 >::is_fill (long bits, unsigned short partitionIndex) inline private
Definition at line 75 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 4 >::is_fill (long bits, unsigned short partitionIndex) inline private
Definition at line 83 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 8 >::is_fill (long bits, unsigned short partitionIndex) inline private
Definition at line 93 of file PWAHBitSet.cpp.
template<unsigned int P> static bool PWAHBitSet< P >::is_fill (long bits, unsigned short partitionIndex) inline static private
template<unsigned int P> bool PWAHBitSet< P >::is_literal (long bits, unsigned short partitionIndex) inline static private
Checks whether the partition with index 'partitionIndex' within 'bits' consists of literal.
Definition at line 261 of file PWAHBitSet.cpp.
template<unsigned int P> static bool PWAHBitSet< P >::is_literal_onefill (long bits, unsigned short partitionIndex) inline static private
template<> bool PWAHBitSet< 1 >::is_literal_onefill (long bits, unsigned short partitionIndex) inline private
Definition at line 268 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 2 >::is_literal_onefill (long bits, unsigned short partitionIndex) inline private
Definition at line 271 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 4 >::is_literal_onefill (long bits, unsigned short partitionIndex) inline private
Definition at line 279 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 8 >::is_literal_onefill (long bits, unsigned short partitionIndex) inline private
Definition at line 292 of file PWAHBitSet.cpp.
template<unsigned int P> static bool PWAHBitSet< P >::is_literal_zerofill (long bits, unsigned short partitionIndex) inline static private
template<> bool PWAHBitSet< 1 >::is_literal_zerofill (long bits, unsigned short partitionIndex) inline private
Definition at line 317 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 2 >::is_literal_zerofill (long bits, unsigned short partitionIndex) inline private
Definition at line 320 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 4 >::is_literal_zerofill (long bits, unsigned short partitionIndex) inline private
Definition at line 325 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 8 >::is_literal_zerofill (long bits, unsigned short partitionIndex) inline private
Definition at line 332 of file PWAHBitSet.cpp.
template<unsigned int P> static bool PWAHBitSet< P >::is_onefill (long bits, unsigned short partitionIndex) static private
template<> bool PWAHBitSet< 1 >::is_onefill (long bits, unsigned short partitionIndex) private
Definition at line 111 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 2 >::is_onefill (long bits, unsigned short partitionIndex) private
Definition at line 115 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 4 >::is_onefill (long bits, unsigned short partitionIndex) private
Definition at line 123 of file PWAHBitSet.cpp.
template<> bool PWAHBitSet< 8 >::is_onefill (long bits, unsigned short partitionIndex) private
Definition at line 133 of file PWAHBitSet.cpp.
template<unsigned int P> bool PWAHBitSet< P >::is_zerofill (long bits, unsigned short partitionIndex) static private
Checks whether the partition with index 'partitionIndex' within 'bits' consists of a 0-fill.
Generic implementation stated below works just fine, but is slower... template<unsigned int P> inline short PWAHBitSet<P>::blocks_num_partitions(int numBlocks){ number of bits available for expressing fill length const short flBits = _blockSize - 1;
Number of bits required to store a specific integer value const int numBits = log2(numBlocks) + 1;
Compute number of partitions required to store the number of blocks, without having to call ceil(...) return (numBits + flBits - 1) / flBits; }
Definition at line 254 of file PWAHBitSet.cpp.
template<unsigned int P> BitSetIterator * PWAHBitSet< P >::iterator () virtual
Implements BitSet.
Definition at line 1636 of file PWAHBitSet.cpp.
template<unsigned int P> const long PWAHBitSet< P >::memoryUsage ()
Definition at line 1626 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::multiOr (PWAHBitSet< P > ** bitSets, unsigned int numBitSets, PWAHBitSet< P > * result) static
Merges multiple WAHBitSet objects into a single WAHBitSet by computing the logical OR.
Parameters
bitSets the source WAHBitSet objects
numBitSets the number of source WAHBitSet objects
result pointer to a WAHBitSet to store the result of the logical OR
Definition at line 1176 of file PWAHBitSet.cpp.
References PWAHBitSet< P >::_blockSize, PWAHBitSet< P >::_lastBitIndex, PWAHBitSet< P >::_plainBlockIndex, PWAHBitSet< P >::_words, PWAHBitSet< P >::addFill(), PWAHBitSet< P >::addLiteral(), PWAHBitSet< P >::countNumberOfBlocks(), PWAHBitSet< P >::decompressLastBlock(), PWAHBitSet< P >::size(), and PWAHBitSet< P >::toString().
template<unsigned int P> void PWAHBitSet< P >::popLastPartition () private
Removes the last partition. This will effectively remove one or more blocks.
This function will update _compressedWords and _lastUsedPartition
Definition at line 1535 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::reset_incr_get_indices ()
Resets the indices used for the 'incr_get' method.
Complexity: O(1)
See Also
incr_get(unsigned int)
Definition at line 577 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::set (unsigned int bitIndex) virtual
Sets the bit with index 'bitIndex' in this PWAHBitSet to '1'.
Reimplemented from BitSet.
Definition at line 779 of file PWAHBitSet.cpp.
template<unsigned int P> void PWAHBitSet< P >::set (unsigned int bitIndex, bool value) virtual
Implements BitSet.
Definition at line 783 of file PWAHBitSet.cpp.
References L_CLEAR_BIT, and L_SET_BIT.
template<unsigned int P> void PWAHBitSet< P >::setIndexChunkSize (int chunkSize) static
Definition at line 541 of file PWAHBitSet.cpp.
Referenced by main().
template<unsigned int P> void PWAHBitSet< P >::setIndexEntry (unsigned int chunkIndex, int indexWord, int indexPartition, int indexPartitionOffset) private
This method will set the search location for the specific chunk to the specified word, partition and partitionOffset.
Example (chunk size = 1000, PWAHBitSet<8>, block size = 7): Suppose a fill consisting of 8 words is added to the PWAHBitSet<8>. The fill is located in the word with index 39, in partition with index 2. The first fill block has index 140 and contains bit indices 980 to 986. The last word of the fill has index 147 and contains bit indices 1029 to 1035. The chunk size specifies that the location of the blocks containing bits 0, 1000, 2000, (...) should be explicitly stored. The bit with index 1000 is located within block 142, the third block in the fill. Directly after adding the partition with the fill containing bit 1000, this method should be called with the following parameters: chunkIndex = 1, indexWord = 39, indexPartition = 2, indexPartitionOffset = 3
Parameters
chunkIndex the chunk index of the chunk to register
indexWord the word index in which the chunk starts
indexPartition the partition index in which the chunk starts
indexPartitionOffset the offset (in blocks) within the partition
Definition at line 1055 of file PWAHBitSet.cpp.
template<unsigned int P> const unsigned int PWAHBitSet< P >::size () virtual
Implements BitSet.
Definition at line 770 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> string PWAHBitSet< P >::toBitString (long value) static
Definition at line 504 of file PWAHBitSet.cpp.
References L_GET_BIT.
Referenced by PWAHBitSetIterator< P >::next().
template<unsigned int P> const string PWAHBitSet< P >::toString () virtual
Reimplemented from BitSet.
Definition at line 1645 of file PWAHBitSet.cpp.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> void PWAHBitSet< P >::updateIndex (int numBlocks, int firstBlockIndex) private
When necessary, updates the search indices of this PWAHBitSet. This method must be called after having actually added a partition.
This method will decide whether it is necessary to add an entry to the list of search indices, based on the two parameters. If it turns out to be unnecessary to add information to the search indices, the method will simply do nothing and return.
Parameters
numBlocks the number of blocks in the last added partition
firstBlockIndex the index of the first block which was added to the partition
Definition at line 998 of file PWAHBitSet.cpp.
Friends And Related Function Documentation
template<unsigned int P> friend class BitSetTester< PWAHBitSet< P > > friend
Definition at line 60 of file PWAHBitSet.h.
template<unsigned int P> friend class PWAHBitSetIterator< P > friend
Definition at line 59 of file PWAHBitSet.h.
Member Data Documentation
template<unsigned int P> const int PWAHBitSet< P >::_blockSize static private
Definition at line 64 of file PWAHBitSet.h.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> long PWAHBitSet< P >::_incr_get_BlockIndex private
Definition at line 92 of file PWAHBitSet.h.
template<unsigned int P> unsigned int PWAHBitSet< P >::_incr_get_PartitionIndex private
Current partition index for use in the PWAHBitSet::incr_get(unsigned int) method
See Also
PWAHBitSet::incr_get(unsigned int)
Definition at line 91 of file PWAHBitSet.h.
template<unsigned int P> unsigned int PWAHBitSet< P >::_incr_get_WordIndex private
Current word index for use in the PWAHBitSet::incr_get(unsigned int) method
See Also
PWAHBitSet::incr_get(unsigned int)
Definition at line 84 of file PWAHBitSet.h.
template<unsigned int P> int PWAHBitSet< P >::_indexChunkSize static private
Definition at line 67 of file PWAHBitSet.h.
template<unsigned int P> vector<unsigned short> PWAHBitSet< P >::_indexPartition private
Definition at line 76 of file PWAHBitSet.h.
template<unsigned int P> vector<int> PWAHBitSet< P >::_indexPartitionOffset private
Definition at line 77 of file PWAHBitSet.h.
template<unsigned int P> vector<int> PWAHBitSet< P >::_indexWord private
Definition at line 75 of file PWAHBitSet.h.
template<unsigned int P> long PWAHBitSet< P >::_lastBitIndex private
Definition at line 70 of file PWAHBitSet.h.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> unsigned short PWAHBitSet< P >::_lastUsedPartition private
Definition at line 71 of file PWAHBitSet.h.
template<unsigned int P> const long PWAHBitSet< P >::_maxBlocksPerFill static private
Definition at line 63 of file PWAHBitSet.h.
template<unsigned int P> const int PWAHBitSet< P >::_partitionOffsets[P] static private
Definition at line 65 of file PWAHBitSet.h.
template<unsigned int P> long PWAHBitSet< P >::_plainBlockIndex private
Definition at line 69 of file PWAHBitSet.h.
Referenced by PWAHBitSet< P >::multiOr().
template<unsigned int P> const bool PWAHBitSet< P >::_VERIFY = false static private
Definition at line 66 of file PWAHBitSet.h.
template<unsigned int P> vector<long> PWAHBitSet< P >::_words private
Definition at line 74 of file PWAHBitSet.h.
Referenced by PWAHBitSet< P >::multiOr().
The documentation for this class was generated from the following files:
src/datastructures/bitsets/pwah/PWAHBitSet.h
src/datastructures/bitsets/pwah/PWAHBitSet.cpp