PWAHStackTC: BitSet Class Reference
BitSet Class Reference abstract
#include <BitSet.h>
Public Member Functions
BitSet ()
virtual ~BitSet ()
virtual const string toString ()
virtual const bool equals (BitSet *otherBitSet)
virtual const unsigned int size ()=0
virtual void clear ()=0
virtual void set (unsigned int bitIndex, bool value)=0
virtual void set (unsigned int bitIndex)
virtual const bool get (unsigned int bitIndex)=0
virtual string bsImplementationName ()=0
virtual BitSetIterator * iterator ()=0
virtual const int blocksize ()=0
Detailed Description
Definition at line 26 of file BitSet.h.
Constructor & Destructor Documentation
BitSet::BitSet ()
Definition at line 24 of file BitSet.cpp.
BitSet::~BitSet () virtual
Definition at line 25 of file BitSet.cpp.
Member Function Documentation
virtual const int BitSet::blocksize () pure virtual
Implemented in WAHBitSet, PWAHBitSet< P >, DynamicBitSet, IntervalBitSet, and StaticBitSet.
virtual string BitSet::bsImplementationName () pure virtual
Implemented in PWAHBitSet< P >, PWAHBitSet< P >, PWAHBitSet< P >, PWAHBitSet< P >, WAHBitSet, PWAHBitSet< P >, DynamicBitSet, StaticBitSet, and IntervalBitSet.
virtual void BitSet::clear () pure virtual
Implemented in WAHBitSet, IntervalBitSet, DynamicBitSet, PWAHBitSet< P >, and StaticBitSet.
const bool BitSet::equals (BitSet * otherBitSet) virtual
Reimplemented in IntervalBitSet.
Definition at line 27 of file BitSet.cpp.
References get(), size(), and toString().
virtual const bool BitSet::get (unsigned int bitIndex) pure virtual
Implemented in WAHBitSet, IntervalBitSet, DynamicBitSet, PWAHBitSet< P >, and StaticBitSet.
Referenced by equals(), and PWAHStackTC< B >::tcToString().
virtual BitSetIterator* BitSet::iterator () pure virtual
Implemented in WAHBitSet, PWAHBitSet< P >, StaticBitSet, DynamicBitSet, and IntervalBitSet.
Referenced by IntervalBitSet::copy().
virtual void BitSet::set (unsigned int bitIndex, bool value) pure virtual
Implemented in WAHBitSet, DynamicBitSet, IntervalBitSet, StaticBitSet, and PWAHBitSet< P >.
void BitSet::set (unsigned int bitIndex) virtual
Reimplemented in WAHBitSet, IntervalBitSet, DynamicBitSet, StaticBitSet, and PWAHBitSet< P >.
Definition at line 52 of file BitSet.cpp.
virtual const unsigned int BitSet::size () pure virtual
Implemented in WAHBitSet, DynamicBitSet, PWAHBitSet< P >, StaticBitSet, and IntervalBitSet.
Referenced by equals().
const string BitSet::toString () virtual
Reimplemented in WAHBitSet, PWAHBitSet< P >, DynamicBitSet, StaticBitSet, and IntervalBitSet.
Definition at line 56 of file BitSet.cpp.
Referenced by equals().
The documentation for this class was generated from the following files:
src/datastructures/bitsets/BitSet.h
src/datastructures/bitsets/BitSet.cpp