PWAHStackTC: TransitiveClosureAlgorithm Class Reference
TransitiveClosureAlgorithm Class Reference abstract
#include <TransitiveClosureAlgorithm.h>
Public Member Functions
TransitiveClosureAlgorithm ()
virtual ~TransitiveClosureAlgorithm ()
virtual void computeTransitiveClosure (bool reflexitive, bool storeComponentMembers, int minOutDegreeForMultiOR)=0
virtual string tcToString ()=0
virtual long countNumberOfEdgesInTC ()=0
virtual long countNumberOfEdgesInCondensedTC ()=0
virtual long countNumberOfEdgesInCondensedTC (bool ignoreSelfLoops, bool ignoreSingletonSelfLoops)=0
virtual int getNumberOfComponents ()=0
virtual void writeToChacoFile (string filename)=0
virtual bool reachable (unsigned int src, unsigned int dst)=0
virtual long memoryUsedByBitSets ()=0
virtual long totalMemoryUsage ()=0
virtual string getStatistics ()=0
virtual string algorithmName ()=0
virtual long memoryUsedByIntervalLists ()=0
virtual double computeAverageLocalClusteringCoefficient ()=0
Detailed Description
Definition at line 27 of file TransitiveClosureAlgorithm.h.
Constructor & Destructor Documentation
TransitiveClosureAlgorithm::TransitiveClosureAlgorithm ()
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 22 of file TransitiveClosureAlgorithm.cpp.
TransitiveClosureAlgorithm::~TransitiveClosureAlgorithm () virtual
Definition at line 24 of file TransitiveClosureAlgorithm.cpp.
Member Function Documentation
virtual string TransitiveClosureAlgorithm::algorithmName () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main(), and Validator::validate().
virtual double TransitiveClosureAlgorithm::computeAverageLocalClusteringCoefficient () pure virtual
Implemented in PWAHStackTC< B >.
virtual void TransitiveClosureAlgorithm::computeTransitiveClosure (bool reflexitive, bool storeComponentMembers, int minOutDegreeForMultiOR) pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main(), and Validator::validate().
virtual long TransitiveClosureAlgorithm::countNumberOfEdgesInCondensedTC () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main().
virtual long TransitiveClosureAlgorithm::countNumberOfEdgesInCondensedTC (bool ignoreSelfLoops, bool ignoreSingletonSelfLoops) pure virtual
Implemented in PWAHStackTC< B >.
virtual long TransitiveClosureAlgorithm::countNumberOfEdgesInTC () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main(), and Validator::validate().
virtual int TransitiveClosureAlgorithm::getNumberOfComponents () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main().
virtual string TransitiveClosureAlgorithm::getStatistics () pure virtual
Implemented in PWAHStackTC< B >, and PWAHStackTC< B >.
Referenced by main().
virtual long TransitiveClosureAlgorithm::memoryUsedByBitSets () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main(), and Validator::validate().
virtual long TransitiveClosureAlgorithm::memoryUsedByIntervalLists () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main().
virtual bool TransitiveClosureAlgorithm::reachable (unsigned int src, unsigned int dst) pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main().
virtual string TransitiveClosureAlgorithm::tcToString () pure virtual
Implemented in PWAHStackTC< B >.
virtual long TransitiveClosureAlgorithm::totalMemoryUsage () pure virtual
Implemented in PWAHStackTC< B >.
Referenced by main().
virtual void TransitiveClosureAlgorithm::writeToChacoFile (string filename) pure virtual
Implemented in PWAHStackTC< B >.
The documentation for this class was generated from the following files:
src/algorithms/TransitiveClosureAlgorithm.h
src/algorithms/TransitiveClosureAlgorithm.cpp