PWAHStackTC: PWAHBitSetIterator< P > Class Template Reference
PWAHBitSetIterator< P > Class Template Reference
#include <PWAHBitSet.h>
Public Member Functions
PWAHBitSetIterator (PWAHBitSet< P > *wahBitSet)
virtual ~PWAHBitSetIterator ()
bool hasNext ()
int next ()
void reset ()
Public Member Functions inherited from BitSetIterator
BitSetIterator ()
virtual ~BitSetIterator ()
Private Attributes
PWAHBitSet< P > * _bitSet
bool _atStart
bool _atEnd
unsigned int _lastBlockIndex
int _lastBlockBitIndex
unsigned int _lastWordIndex
unsigned int _lastPartitionBlockIndex
unsigned short _lastWordPartitionIndex
Detailed Description
template<unsigned int P>
class PWAHBitSetIterator< P >
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 29 of file PWAHBitSet.h.
Constructor & Destructor Documentation
template<unsigned int P> PWAHBitSetIterator< P >::PWAHBitSetIterator (PWAHBitSet< P > * pwbs)
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 24 of file PWAHBitSetIterator.cpp.
template<unsigned int P> PWAHBitSetIterator< P >::~PWAHBitSetIterator () virtual
Definition at line 29 of file PWAHBitSetIterator.cpp.
Member Function Documentation
template<unsigned int P> bool PWAHBitSetIterator< P >::hasNext () virtual
Determines whether there actually is a next set bit
Implements BitSetIterator.
Definition at line 31 of file PWAHBitSetIterator.cpp.
template<unsigned int P> int PWAHBitSetIterator< P >::next () virtual
Returns the index of the next set bit. Will return -1 if there is no next set bit
Implements BitSetIterator.
Definition at line 46 of file PWAHBitSetIterator.cpp.
References PWAHBitSet< P >::blocks_num_partitions(), PWAHBitSet< P >::extract_partition(), PWAHBitSet< P >::fill_length(), L_GET_BIT, and PWAHBitSet< P >::toBitString().
template<unsigned int P> void PWAHBitSetIterator< P >::reset () virtual
Implements BitSetIterator.
Definition at line 35 of file PWAHBitSetIterator.cpp.
Member Data Documentation
template<unsigned int P> bool PWAHBitSetIterator< P >::_atEnd private
Definition at line 30 of file PWAHBitSetIterator.h.
template<unsigned int P> bool PWAHBitSetIterator< P >::_atStart private
Definition at line 29 of file PWAHBitSetIterator.h.
template<unsigned int P> PWAHBitSet<P>* PWAHBitSetIterator< P >::_bitSet private
Definition at line 28 of file PWAHBitSetIterator.h.
template<unsigned int P> int PWAHBitSetIterator< P >::_lastBlockBitIndex private
Definition at line 32 of file PWAHBitSetIterator.h.
template<unsigned int P> unsigned int PWAHBitSetIterator< P >::_lastBlockIndex private
Definition at line 31 of file PWAHBitSetIterator.h.
template<unsigned int P> unsigned int PWAHBitSetIterator< P >::_lastPartitionBlockIndex private
Definition at line 34 of file PWAHBitSetIterator.h.
template<unsigned int P> unsigned int PWAHBitSetIterator< P >::_lastWordIndex private
Definition at line 33 of file PWAHBitSetIterator.h.
template<unsigned int P> unsigned short PWAHBitSetIterator< P >::_lastWordPartitionIndex private
Definition at line 35 of file PWAHBitSetIterator.h.
The documentation for this class was generated from the following files:
src/datastructures/bitsets/pwah/PWAHBitSet.h
src/datastructures/bitsets/pwah/PWAHBitSetIterator.h
src/datastructures/bitsets/pwah/PWAHBitSetIterator.cpp