PWAHStackTC: IntervalBitSet Class Reference
IntervalBitSet Class Reference
#include <IntervalBitSet.h>
Public Member Functions
IntervalBitSet ()
virtual ~IntervalBitSet ()
long memoryUsage ()
const string toString ()
const string toDetailString ()
const bool equals (BitSet *otherBitSet)
const unsigned int size ()
const unsigned int numberOfIntervals ()
void clear ()
void set (unsigned int bitIndex, bool value)
void set (unsigned int bitIndex)
const bool get (unsigned int bitIndex)
string bsImplementationName ()
BitSetIterator * iterator ()
const int blocksize ()
Public Member Functions inherited from BitSet
BitSet ()
virtual ~BitSet ()
Static Public Member Functions
static void copy (BitSet *otherBitSet, IntervalBitSet *result)
static void multiOr (IntervalBitSet **bitSets, unsigned int numBitSets, IntervalBitSet *result)
static IntervalBitSet * constructByOr (const IntervalBitSet *first, const IntervalBitSet *second)
Private Member Functions
void addInterval (int lower, int upper)
Private Attributes
int _lastBitTouched
vector< int > _lower
vector< int > _upper
Friends
class IntervalBitSetIterator
Detailed Description
Definition at line 27 of file IntervalBitSet.h.
Constructor & Destructor Documentation
IntervalBitSet::IntervalBitSet ()
Definition at line 28 of file IntervalBitSet.cpp.
IntervalBitSet::~IntervalBitSet () virtual
Definition at line 32 of file IntervalBitSet.cpp.
Member Function Documentation
void IntervalBitSet::addInterval (int lower, int upper) private
Definition at line 246 of file IntervalBitSet.cpp.
Referenced by multiOr().
const int IntervalBitSet::blocksize () virtual
Implements BitSet.
Definition at line 158 of file IntervalBitSet.cpp.
string IntervalBitSet::bsImplementationName () virtual
Implements BitSet.
Definition at line 150 of file IntervalBitSet.cpp.
void IntervalBitSet::clear () virtual
Implements BitSet.
Definition at line 96 of file IntervalBitSet.cpp.
IntervalBitSet * IntervalBitSet::constructByOr (const IntervalBitSet * first, const IntervalBitSet * second) static
Definition at line 266 of file IntervalBitSet.cpp.
void IntervalBitSet::copy (BitSet * otherBitSet, IntervalBitSet * result) static
Definition at line 57 of file IntervalBitSet.cpp.
References BitSet::iterator(), BitSetIterator::next(), and set().
Referenced by PWAHStackTC< B >::memoryUsedByIntervalLists().
const bool IntervalBitSet::equals (BitSet * otherBitSet) virtual
Reimplemented from BitSet.
Definition at line 83 of file IntervalBitSet.cpp.
const bool IntervalBitSet::get (unsigned int bitIndex) virtual
Implements BitSet.
Definition at line 114 of file IntervalBitSet.cpp.
BitSetIterator * IntervalBitSet::iterator () virtual
Implements BitSet.
Definition at line 154 of file IntervalBitSet.cpp.
long IntervalBitSet::memoryUsage ()
Definition at line 68 of file IntervalBitSet.cpp.
Referenced by PWAHStackTC< B >::memoryUsedByIntervalLists().
void IntervalBitSet::multiOr (IntervalBitSet ** bitSets, unsigned int numBitSets, IntervalBitSet * result) static
Definition at line 162 of file IntervalBitSet.cpp.
References _lastBitTouched, _lower, _upper, addInterval(), size(), and toString().
const unsigned int IntervalBitSet::numberOfIntervals ()
Definition at line 87 of file IntervalBitSet.cpp.
void IntervalBitSet::set (unsigned int bitIndex, bool value) virtual
Implements BitSet.
Definition at line 102 of file IntervalBitSet.cpp.
Referenced by copy().
void IntervalBitSet::set (unsigned int bitIndex) virtual
Reimplemented from BitSet.
Definition at line 34 of file IntervalBitSet.cpp.
const unsigned int IntervalBitSet::size () virtual
Implements BitSet.
Definition at line 92 of file IntervalBitSet.cpp.
Referenced by multiOr().
const string IntervalBitSet::toDetailString ()
const string IntervalBitSet::toString () virtual
Reimplemented from BitSet.
Definition at line 72 of file IntervalBitSet.cpp.
Referenced by multiOr().
Friends And Related Function Documentation
friend class IntervalBitSetIterator friend
Definition at line 51 of file IntervalBitSet.h.
Member Data Documentation
int IntervalBitSet::_lastBitTouched private
Definition at line 54 of file IntervalBitSet.h.
Referenced by multiOr().
vector<int> IntervalBitSet::_lower private
Definition at line 55 of file IntervalBitSet.h.
Referenced by multiOr(), and IntervalBitSetIterator::next().
vector<int> IntervalBitSet::_upper private
Definition at line 56 of file IntervalBitSet.h.
Referenced by multiOr(), and IntervalBitSetIterator::next().
The documentation for this class was generated from the following files:
src/datastructures/bitsets/interval/IntervalBitSet.h
src/datastructures/bitsets/interval/IntervalBitSet.cpp