PWAHStackTC: BitSetIterator Class Reference
BitSetIterator Class Reference abstract
#include <BitSetIterator.h>
Public Member Functions
BitSetIterator ()
virtual ~BitSetIterator ()
virtual int next ()=0
virtual bool hasNext ()=0
virtual void reset ()=0
Detailed Description
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 23 of file BitSetIterator.h.
Constructor & Destructor Documentation
BitSetIterator::BitSetIterator ()
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 22 of file BitSetIterator.cpp.
BitSetIterator::~BitSetIterator () virtual
Definition at line 24 of file BitSetIterator.cpp.
Member Function Documentation
virtual bool BitSetIterator::hasNext () pure virtual
Implemented in WAHBitSetIterator, PWAHBitSetIterator< P >, and IntervalBitSetIterator.
virtual int BitSetIterator::next () pure virtual
Implemented in WAHBitSetIterator, PWAHBitSetIterator< P >, and IntervalBitSetIterator.
Referenced by PWAHStackTC< B >::computeLocalClusteringCoefficient(), IntervalBitSet::copy(), PWAHStackTC< B >::countNumberOfEdgesInCondensedTC(), and PWAHStackTC< B >::countNumberOfEdgesInTC().
virtual void BitSetIterator::reset () pure virtual
Implemented in WAHBitSetIterator, PWAHBitSetIterator< P >, and IntervalBitSetIterator.
The documentation for this class was generated from the following files:
src/datastructures/bitsets/BitSetIterator.h
src/datastructures/bitsets/BitSetIterator.cpp