PWAHStackTC: StaticBitSet Class Reference
StaticBitSet Class Reference
#include <StaticBitSet.h>
Public Member Functions
StaticBitSet (unsigned int capacity)
virtual ~StaticBitSet ()
void init (unsigned int initialCapacity=64)
void clear ()
void set (unsigned int bitIndex)
void set (unsigned int bitIndex, bool value)
const bool get (unsigned int bitIndex)
const string toString ()
string toBitString (long value)
const unsigned int capacity ()
const unsigned int size ()
string bsImplementationName ()
const int blocksize ()
BitSetIterator * iterator ()
Public Member Functions inherited from BitSet
BitSet ()
virtual ~BitSet ()
virtual const bool equals (BitSet *otherBitSet)
Private Attributes
unsigned int _capacity
int _firstBitSet
int _lastBitSet
unsigned int _numLongs
long * _bits
Detailed Description
Copyright 2010-2011 Sebastiaan J. van Schaik
This file is part of PWAHStackTC.
PWAHStackTC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
PWAHStackTC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with PWAHStackTC. If not, see http://www.gnu.org/licenses/.
Definition at line 25 of file StaticBitSet.h.
Constructor & Destructor Documentation
StaticBitSet::StaticBitSet (unsigned int capacity)
Definition at line 34 of file StaticBitSet.cpp.
StaticBitSet::~StaticBitSet () virtual
Definition at line 38 of file StaticBitSet.cpp.
Member Function Documentation
const int StaticBitSet::blocksize () virtual
Implements BitSet.
Definition at line 116 of file StaticBitSet.cpp.
string StaticBitSet::bsImplementationName () virtual
Implements BitSet.
Definition at line 120 of file StaticBitSet.cpp.
const unsigned int StaticBitSet::capacity ()
Definition at line 104 of file StaticBitSet.cpp.
void StaticBitSet::clear () virtual
Implements BitSet.
Definition at line 108 of file StaticBitSet.cpp.
const bool StaticBitSet::get (unsigned int bitIndex) virtual
Implements BitSet.
Definition at line 77 of file StaticBitSet.cpp.
References L_GET_BIT.
Referenced by Graph::computeLocalClusteringCoefficient(), and PWAHStackTC< B >::computeLocalClusteringCoefficient().
void StaticBitSet::init (unsigned int initialCapacity = 64)
Definition at line 43 of file StaticBitSet.cpp.
BitSetIterator * StaticBitSet::iterator () virtual
Implements BitSet.
Definition at line 124 of file StaticBitSet.cpp.
void StaticBitSet::set (unsigned int bitIndex) virtual
Reimplemented from BitSet.
Definition at line 53 of file StaticBitSet.cpp.
Referenced by Graph::computeLocalClusteringCoefficient(), and PWAHStackTC< B >::computeLocalClusteringCoefficient().
void StaticBitSet::set (unsigned int bitIndex, bool value) virtual
Implements BitSet.
Definition at line 57 of file StaticBitSet.cpp.
References L_CLEAR_BIT, and L_SET_BIT.
const unsigned int StaticBitSet::size () virtual
Implements BitSet.
Definition at line 100 of file StaticBitSet.cpp.
string StaticBitSet::toBitString (long value)
Definition at line 90 of file StaticBitSet.cpp.
References L_GET_BIT.
const string StaticBitSet::toString () virtual
Reimplemented from BitSet.
Definition at line 82 of file StaticBitSet.cpp.
Member Data Documentation
long* StaticBitSet::_bits private
Definition at line 30 of file StaticBitSet.h.
unsigned int StaticBitSet::_capacity private
Definition at line 27 of file StaticBitSet.h.
int StaticBitSet::_firstBitSet private
Definition at line 28 of file StaticBitSet.h.
int StaticBitSet::_lastBitSet private
Definition at line 28 of file StaticBitSet.h.
unsigned int StaticBitSet::_numLongs private
Definition at line 29 of file StaticBitSet.h.
The documentation for this class was generated from the following files:
src/datastructures/bitsets/StaticBitSet.h
src/datastructures/bitsets/StaticBitSet.cpp